"""Opt-in live model/knowledge eval; no HubSpot sends or customer DB writes.

Run: python evaluate_context.py --live
Optional --supabase-check writes/removes ONE synthetic checkpoint in its own
namespace to verify the existing database contract; never touches real tickets.
"""
import argparse
from datetime import datetime, timezone
import json
import os
import uuid
from unittest.mock import patch


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--live", action="store_true", required=True)
    parser.add_argument("--supabase-check", action="store_true")
    options = parser.parse_args()
    os.environ.update(HUBSPOT_POLLING_ENABLED="false", SUPABASE_CONVERSATION_MEMORY_ENABLED="false", AGNO_TELEMETRY="false")
    import salomao_agent as module
    from conversation_memory import SupabaseConversationMemory

    if options.supabase_check:
        memory = SupabaseConversationMemory()
        thread = "synthetic_context_eval_" + uuid.uuid4().hex
        messages = [{"id": "synthetic-message", "text": "Teste sintético de memória, sem dados de cliente.",
                     "created_at": datetime.now(timezone.utc).isoformat(), "is_from_visitor": True}]
        try:
            saved = memory.save(thread, messages)
            restored = memory.load(thread) if saved else []
            print(json.dumps({"supabase_checkpoint_saved": saved, "restored_messages": len(restored)}))
            assert saved and len(restored) == 1, "Supabase checkpoint could not be verified"
        finally:
            # Exact UUID generated by this run, in the reserved synthetic namespace.
            result = memory.client.delete("salomao_sessions", params={"session_id": "eq." + memory.session_id(thread)},
                headers={"Prefer": "return=representation"})
            result.raise_for_status()
            print(json.dumps({"synthetic_rows_removed": len(result.json())}))
            memory.client.close()

    history = [
        {"role": "user", "content": "como faço um novo membro?"},
        {"role": "assistant", "content": "Para cadastrar um membro, acesse Pessoas > +Novo > Membro. "
         "Os campos obrigatórios informados na documentação são nome completo, sexo, data de nascimento, país e endereço. "
         "Fonte: https://portal.inchurch.com.br/pt-br/cadastro-de-membros-manual"},
    ]
    with patch.object(module, "db"), patch.object(module.salomao, "_record_turn_metric"), \
         patch.object(module.salomao, "refresh_conversation_summary"):
        for question in ("quais são os obrigatórios?", "e telefone, precisa?", "quantas libertadores o flamengo tem"):
            result = module.salomao.process_message(question, session_id="synthetic-context-evaluation",
                originating_channel="whatsapp", conversation_history=history)
            print(json.dumps({"question": question, "status": result.get("answer_status"),
                "response": result["response"], "sources": result.get("sources", [])}, ensure_ascii=False))
            assert result.get("answer_status") not in {"scope_blocked", "unavailable"}, "Conversation regression"
            if "obrigatórios" in question:
                assert "nome" in result["response"].lower() and "membro" in result["response"].lower()
            if "libertadores" not in question:
                history.extend([{"role": "user", "content": question}, {"role": "assistant", "content": result["response"]}])
            else:
                assert result.get("answer_status") == "out_of_scope"


if __name__ == "__main__":
    main()
